apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cat-webapp
  name: cat-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cat-webapp
    spec:
      containers:
      - image: nilli9990/cat-webapp
        name: cat-webapp
        env:
        - name: CAT_INDEX
          value: "2"
        ports:
        - containerPort: 5000
        resources: {}
