apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginxsecretenvfrom
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    envFrom:
      - secretRef:
          name: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
