apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxhostpath
  name: nginxhostpath
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        port: 80
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: pv-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: pv-storage
    hostPath:
      path: /tmp/storage/data
      type: DirectoryOrCreate
status: {}
