apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxinit
  name: nginxinit
spec:
  initContainers:
  - name: dummy
    image: busybox:1.28
    command: ['sh', '-c', 'echo running init! && sleep 30']
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        port: 80
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
