# Default values for catwebapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environmentLabel: prod

image:
  repository: nilli9990/cat-webapp
  tag: "1.0"

service:
  type: NodePort
  nodePort: 14000


