apiVersion: v1
kind: Service
metadata:
  name: cat-svc
  labels:
    {{- include "catwebapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "catwebapp.labels" . | nindent 4 }}
