apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginxinvalidcommand
spec:
  containers:
  - image: nginx
    name: nginx
    command: ["bla"]
    livenessProbe:
      httpGet:
        port: 80
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
