apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxpvc
  name: nginxpvc
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        port: 80
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
