apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxempty
  name: nginxempty
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        port: 80
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: "/cache"
      name: pv-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: pv-storage
    emptyDir: {}
status: {}
