apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxpvc
  name: nginxpvc
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        port: 80
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: "/var/log/nginx"
      name: pv-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pv-claim
status: {}
