bases:
  - ../base

commonLabels:
 env: prd

namespace: niels

images:
- name: cat-webapp
  newName: nilli9990/cat-webapp
  newTag: "1.1"

patchesStrategicMerge:
- numberReplicas.yaml
- nodePort.yaml

