apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubectl
  name: kubectl
spec:
  serviceAccountName: kubectl
  containers:
    - image: bitnami/kubectl:1.22-debian-10
      name: kubectl
      command:
        - tail
        - -f
        - /dev/null
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
