apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-0-volume
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/tmp/statefulset/data"
